### PR TITLE
Updating Node dependencies (such as AngularJS, TypeScript, and RxJS)

### PR DESCRIPTION
**Pull request by b-long**
Hi @RedFroggy, thanks for providing this project.  It’s a fantastic resource for people looking to start a project with Spring Boot and Angular2.  In my opinion, it's much more appealing than the [Spring Initializer](http://start.spring.io/) and [JHipster](https://jhipster.github.io/).  I really like this project and hope to help you with it :smile:

This commit is similar to https://github.com/RedFroggy/angular-spring-dynamic-form/pull/4 in that I’m just updating dependencies.  I’ve tested these changes and everything is working as I expect.  However, please review it and test it since you are probably more familiar than I.

Thanks,
b-long

### CODE REVIEW

**Comment by michaeldesigaud** [comment]
Thanks for the feedback and your MR. Can you edit the readme file to set the proper angular version ?
Thx

**Comment by b-long** [comment]
Good catch, sorry about that.  The README is now fixed 👍

**Comment by b-long** [comment]
If you prefer I squash the commits, let me know.

**Comment by michaeldesigaud** [comment]
The PR is ok for me. But i'll do another commit to revert the spring-boot parent version from 1.4.3.RELEASE to 1.3.2.RELEASE because there is an issue with the exec-maven-plugin on windows.
Thanks anyway !

**Pull request merged**
